services:
  jaeger-dev:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_HTTP_CORS_ALLOWED_HEADERS=*
      - COLLECTOR_OTLP_HTTP_CORS_ALLOWED_ORIGINS=*
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
  jaeger-test:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16687:16686"
      - "4319:4318"
    environment:
      - COLLECTOR_OTLP_HTTP_CORS_ALLOWED_HEADERS=*
      - COLLECTOR_OTLP_HTTP_CORS_ALLOWED_ORIGINS=*
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug