// Generated by Wrangler on Fri Sep 06 2024 17:08:58 GMT-0600 (Mountain Daylight Time)
// by running `wrangler types --env dev`

interface Env {
  ENVIRONMENT: string;
  SERVICE_NAME: string;
  WORKOS_API_KEY: string;
  WORKOS_CLIENT_ID: string;
  APP_DB: D1Database;
}
