// Generated by Wrangler on Fri Sep 06 2024 15:44:41 GMT-0600 (Mountain Daylight Time)
// by running `wrangler types`

interface Env {
  ENVIRONMENT: string;
  SERVICE_NAME: string;
  WORKOS_API_KEY: string;
  WORKOS_CLIENT_ID: string;
}
